name = "TriShellFiniteElement"
uuid = "4f2873d8-418d-4a23-a33c-c2fdbebf1db2"
version = "0.1.0"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
Ferrite = "1.3.0"
LinearAlgebra = "1.12.0"
Tensors = "1.16.2"
