name = "TriShellFiniteElement"
uuid = "4f2873d8-418d-4a23-a33c-c2fdbebf1db2"
version = "0.1.0"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"

[compat]
Ferrite = "1.3.0"
